CREATE TABLE user (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NULL DEFAULT NULL,
default_vpa VARCHAR(255) NOT NULL,
status VARCHAR(255) DEFAULT NULL,
`created_on` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
`updated_on` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
PRIMARY KEY (id)
);
CREATE TABLE user_vpa (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NULL DEFAULT NULL,
`created_on` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
`updated_on` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
PRIMARY KEY (id)
);